GET http://localhost:3000/api/v1/books
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDIyYTA4NmRmZTMzOTE3OGMzODFiMWEiLCJuYW1lIjoiQWxqb2huIFZpbGxhcnViaWEiLCJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRQWlF1VjVRNnJJQXJDSVVsQXozQ0l1S0s0M3FxS3R3RThEY3d3UGl0emw5MkRwTGcuckZLUyIsImNyZWF0ZWRBdCI6IjIwMjEtMDItMDlUMTQ6NDc6MzUuMDM4WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDItMDlUMTQ6NDc6MzUuMDM4WiIsIl9fdiI6MCwiaWF0IjoxNjEyODgzODUxfQ.K323XdGj3Wz0wDxTVCEldZzwssSX9b1J4ng3211a_kQ

###

POST http://localhost:3000/api/v1/books
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDIyYTA4NmRmZTMzOTE3OGMzODFiMWEiLCJuYW1lIjoiQWxqb2huIFZpbGxhcnViaWEiLCJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRQWlF1VjVRNnJJQXJDSVVsQXozQ0l1S0s0M3FxS3R3RThEY3d3UGl0emw5MkRwTGcuckZLUyIsImNyZWF0ZWRBdCI6IjIwMjEtMDItMDlUMTQ6NDc6MzUuMDM4WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDItMDlUMTQ6NDc6MzUuMDM4WiIsIl9fdiI6MCwiaWF0IjoxNjEyODgzODUxfQ.K323XdGj3Wz0wDxTVCEldZzwssSX9b1J4ng3211a_kQ
Content-Type: application/json

{
    "title": "C# for Dummies",
    "description": "a programming book for beginners teaches C#.",
    "author_id": "6022a086dfe339178c381b1a"
}

###

PATCH http://localhost:3000/api/v1/books
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDIyYTA4NmRmZTMzOTE3OGMzODFiMWEiLCJuYW1lIjoiQWxqb2huIFZpbGxhcnViaWEiLCJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRQWlF1VjVRNnJJQXJDSVVsQXozQ0l1S0s0M3FxS3R3RThEY3d3UGl0emw5MkRwTGcuckZLUyIsImNyZWF0ZWRBdCI6IjIwMjEtMDItMDlUMTQ6NDc6MzUuMDM4WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDItMDlUMTQ6NDc6MzUuMDM4WiIsIl9fdiI6MCwiaWF0IjoxNjEyODgzODUxfQ.K323XdGj3Wz0wDxTVCEldZzwssSX9b1J4ng3211a_kQ
Content-Type: application/json

{
    "_id": "6022b07e4112481038f07dea",
    "title": "Javascript for Dummies",
    "description": "a programming book for beginners teaches C#.",
    "author_id": "6022a086dfe339178c381b1a"
}

###

DELETE http://localhost:3000/api/v1/books/6022b07e4112481038f07dea
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDIyYTA4NmRmZTMzOTE3OGMzODFiMWEiLCJuYW1lIjoiQWxqb2huIFZpbGxhcnViaWEiLCJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRQWlF1VjVRNnJJQXJDSVVsQXozQ0l1S0s0M3FxS3R3RThEY3d3UGl0emw5MkRwTGcuckZLUyIsImNyZWF0ZWRBdCI6IjIwMjEtMDItMDlUMTQ6NDc6MzUuMDM4WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDItMDlUMTQ6NDc6MzUuMDM4WiIsIl9fdiI6MCwiaWF0IjoxNjEyODgzODUxfQ.K323XdGj3Wz0wDxTVCEldZzwssSX9b1J4ng3211a_kQ